apiVersion: v1
kind: Service
metadata:
  name: grpc_client
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 58080
      targetPort: 8080
  selector:
    app: grpc_client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc_client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc_client
  template:
    metadata:
      labels:
        app: grpc_client
    spec:
      containers:
        - name: spring-boot-istio-client
          image: 1148541663/grpc_client:latest
          imagePullPolicy: Always
          tty: true
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080

